### ISSUE TITLE
Go back to the previous Raspiberry pi Desktop

### ISSUE THREAD

**Issue by WofgangRunas** [josfaber/debian-kiosk-installer#6]
Hey, I have install the kiosk and everything it works perfectly, but how I can stop the scrip to not run the kiosk on the next reboot?
Basically I want go back to the previous Raspberry Pi Desktop.

**Comment by josfaber** [comment]
The script is basically "stuck" in a while loop. So if you stop chromium, it will restart chromium.
If you don't want that you can remove the while loop by removing the lines [while](https://github.com/josfaber/debian-kiosk-installer/blob/master/kiosk-installer.sh#L57), [do](https://github.com/josfaber/debian-kiosk-installer/blob/master/kiosk-installer.sh#L58): and [done &](https://github.com/josfaber/debian-kiosk-installer/blob/master/kiosk-installer.sh#L72)

**Comment by WofgangRunas** [comment]
Thanks for reply! Yes, I did that before but when I reboot the Pi still on the Openbox. I would like to go back to this:

![custom-default2](https://github.com/josfaber/debian-kiosk-installer/assets/65097627/e90df8d4-6e2c-4436-9a2b-410a89678094)

It's possible ? Because now it's showing up the terminal, should I uninstall the openbox ?

**Comment by josfaber** [comment]
Sorry, I misunderstood (I feel like chatGPT now ;-) ) on reboot the script ofcourse runs Chrome again. 

For this to work you could extend the script to write a file like `~/.hasrun` and if that file exists skip opening Chrome. You could also then remove the file so the next time Chrome will run again, effectively alternating between the Chrome app and the desktop.

A quick example
```
# Check if ~/.hasrun exists
if [ -f ~/.hasrun ]; then
    echo "The script has already run. Exiting."
    # if in need of alternating, remove file here (remove comment # below)
    # unlink ~/.hasrun
    exit 1
fi

# If ~/.hasrun doesn't exist, create it and execute echo
touch ~/.hasrun
# do the Chrome loop here
```
